<!--
	Could not resolve host:
		gkskm1438867.br.whoer.net
		rbysz1438864.br.whoer.net
		nl3-speed.whoer.net
		www.tcp.whoer.net
		tcp9.whoer.net
		ua3-speed.whoer.net
		uk2-speed.whoer.net

	OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to:
		ca1-speed.whoer.net
		ca2-speed.whoer.net
		ch1-speed.whoer.net
		ch2-speed.whoer.net
		de1-speed.whoer.net
		de2-speed.whoer.net
		de3-speed.whoer.net
		es1-speed.whoer.net
		fr1-speed.whoer.net
		fr2-speed.whoer.net
		fr3-speed.whoer.net
		hk1-speed.whoer.net
		it1-speed.whoer.net
		nl1-speed.whoer.net
		nl2-speed.whoer.net
		nl88-speed.whoer.net
		nl99-speed.whoer.net
		pl1-speed.whoer.net
		ro1-speed.whoer.net
		ru1-speed.whoer.net
		ru2-speed.whoer.net
		ru3-speed.whoer.net
		ru4-speed.whoer.net
		se1-speed.whoer.net
		se2-speed.whoer.net
		sg1-speed.whoer.net
		tcp.whoer.net
		tr1-speed.whoer.net
		ua1-speed.whoer.net
		ua2-speed.whoer.net
		uk1-speed.whoer.net
		us1-speed.whoer.net
		us2-speed.whoer.net
		us3-speed.whoer.net
		us4-speed.whoer.net

	Connnection Refused:
		mail.whoer.net (r)
		nl33-speed.whoer.net
		nl44-speed.whoer.net
		nl55-speed.whoer.net
		nl66-speed.whoer.net

	Connnection timed out:
		nl4-speed.whoer.net
		nl5-speed.whoer.net

	Failed to connect, No route to host:
		us5-speed.whoer.net

	r: connection refused
-->
<ruleset name="Whoer.net">
	<target host="whoer.net" />
	<target host="www.whoer.net" />
	<!-- hosts referenced here were enumerated by `python3 sublist3r.py -d whoer.net` -->
	<target host="vpnapi.whoer.net"/>
	<target host="wime.whoer.net"/>

	<rule from="^http:" to="https:" />
</ruleset>
